extends Resource
class_name EnemySpawnInstructions
"""
REMOVE REMOVE REMOVE REMOVE REMOVE 
REMOVE REMOVE REMOVE REMOVE REMOVE 
REMOVE REMOVE REMOVE REMOVE REMOVE 
REMOVE REMOVE REMOVE REMOVE REMOVE 
REMOVE REMOVE REMOVE REMOVE REMOVE 
REMOVE REMOVE REMOVE REMOVE REMOVE 

REMOVE REMOVE REMOVE REMOVE REMOVE 
REMOVE REMOVE REMOVE REMOVE REMOVE 
REMOVE REMOVE REMOVE REMOVE REMOVE 
REMOVE REMOVE REMOVE REMOVE REMOVE 

REMOVE REMOVE REMOVE REMOVE REMOVE 
REMOVE REMOVE REMOVE REMOVE REMOVE 
REMOVE REMOVE REMOVE REMOVE REMOVE 
v

"""
var enemy_scenes:Dictionary = {
	
}

@export var spawn_instructions:Array[SingleEnemySpawnInstruction] = []


func add_spawn_instruction(enemy_scene_name:String, position:float, behaviour:int):
	#will add it to the list. 
	pass
